import {
  Home,
  Film,
  Calendar,
  Grid3x3,
  ShoppingCart,
  Ticket,
  Users,
  HelpCircle,
  Mail,
  Headphones,
  Sparkles,
  QrCode,
  Banknote,
  Bell,
  CreditCard,
  History,
  Receipt,
  ReceiptText,
  Wallet,
  Calculator,
  PartyPopper,
  Gift,
  Instagram,
  Building2,
  ScrollText,
  LucideIcon,
} from 'lucide-react';

export interface AdminMenuItem {
  title: string;
  icon: LucideIcon;
  href: string;
  color: string;
  bgColor: string;
}

export const adminMenuItems: AdminMenuItem[] = [
  {
    title: 'Գլխավոր',
    icon: Home,
    href: '/admin',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Հաճախորդի մուտք',
    icon: QrCode,
    href: '/admin/scanner',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Դրամարկղ',
    icon: Banknote,
    href: '/admin/box-office',
    color: 'text-green-600',
    bgColor: 'bg-green-50',
  },
  {
    title: 'ՀԴՄ Agent',
    icon: Receipt,
    href: '/admin/hdm',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
  },
  {
    title: 'Ծախսեր',
    icon: Wallet,
    href: '/admin/expenses',
    color: 'text-rose-600',
    bgColor: 'bg-rose-50',
  },
  {
    title: 'Հաշվապահություն',
    icon: Calculator,
    href: '/admin/accounting',
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
  },
  {
    title: 'Ֆիսկալ կտրոններ',
    icon: ReceiptText,
    href: '/admin/fiscal',
    color: 'text-teal-600',
    bgColor: 'bg-teal-50',
  },
  {
    title: 'Ֆիլմեր',
    icon: Film,
    href: '/admin/movies',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Ցուցադրություններ',
    icon: Calendar,
    href: '/admin/screenings',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
  },
  {
    title: 'Փաթեթների պատվերներ',
    icon: PartyPopper,
    href: '/admin/packages',
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
  },
  {
    title: 'Պրեմիերաներ',
    icon: Sparkles,
    href: '/admin/premieres',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Նստատեղեր',
    icon: Grid3x3,
    href: '/admin/seats',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
  },
  {
    title: 'Ապրանքներ',
    icon: ShoppingCart,
    href: '/admin/products',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50',
  },
  {
    title: 'Ապրանքների միավորներ',
    icon: History,
    href: '/admin/product-units',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50',
  },
  {
    title: 'Տոմսեր',
    icon: Ticket,
    href: '/admin/tickets',
    color: 'text-green-600',
    bgColor: 'bg-green-50',
  },
  {
    title: 'Վճարումներ',
    icon: CreditCard,
    href: '/admin/payments',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
  },

  {
    title: 'Ծանուցումներ',
    icon: Bell,
    href: '/admin/notifications',
    color: 'text-pink-600',
    bgColor: 'bg-pink-50',
  },

  {
    title: 'Օգտատերեր',
    icon: Users,
    href: '/admin/users',
    color: 'text-orange-600',
    bgColor: 'bg-orange-50',
  },
  {
    title: 'Բոնուսային համակարգ',
    icon: Gift,
    href: '/admin/bonus',
    color: 'text-violet-600',
    bgColor: 'bg-violet-50',
  },
  {
    title: 'Հաճախակի հարցեր',
    icon: HelpCircle,
    href: '/admin/faq',
    color: 'text-purple-600',
    bgColor: 'bg-purple-50',
  },
  {
    title: 'Կոնտակտներ',
    icon: Mail,
    href: '/admin/contacts',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50',
  },
  {
    title: 'Աջակցություն',
    icon: Headphones,
    href: '/admin/support',
    color: 'text-red-600',
    bgColor: 'bg-red-50',
  },
  {
    title: 'Ընկերություններ',
    icon: Building2,
    href: '/admin/companies',
    color: 'text-slate-600',
    bgColor: 'bg-slate-50',
  },
  {
    title: 'Պայմանագրեր',
    icon: ScrollText,
    href: '/admin/contracts',
    color: 'text-stone-600',
    bgColor: 'bg-stone-50',
  },
  {
    title: 'SMM',
    icon: Instagram,
    href: '/admin/smm',
    color: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
  },
];
