openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Invoicing"
servers:
  - url: "http://localhost:8080"
    description: Local
paths:
  /tpinfo/tp-info-by-tin:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
                    tin:
                      type: string
                    checkDate:
                      type: string
                      format: date-time
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: false
                    properties:
                      vatNumber:
                        type: string
                        nullable: true
                      vatNumberForDate:
                        type: string
                      name:
                        type: string
                      address:
                        type: string
                      status:
                        type: string
                      checkStatus:
                        type: string
                      organizationalType:
                        type: string
                      orgTypeCode:
                        type: string
                      orgTypeCodeForDate:
                        type: string
                      tin:
                        type: string
                      exitCode:
                        type: string
                  failure:
                    type: object
                    nullable: true
                    properties:
                      code:
                        type: string
                      message:
                        type: string
