openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Invoicing"
servers:
  - url: "http://localhost:8080"
    description: Local
paths:
  /data-sync/country-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/classifier-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/commodity-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/commodity-measure-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/region-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/community-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
  /data-sync/residence-sync:
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
                  properties:
                    clientTin:
                      type: string
                      nullable: true
                    clientUser:
                      type: string
                      nullable: true
      responses:
        "200":
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  payload:
                    type: object
                    nullable: true
                  failure:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
