###
POST http://ews.taxservice.am/taxsystem-fe-ws/taxpayer/loginService
Content-Type: text/xml;charset=UTF-8

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:def="http://www.taxservice.am/tp3/invoice/definitions">
  <soapenv:Header/>
  <soapenv:Body>
    <def:LoginWebRequest Tin="?" Login="?" Password="?" ClientType="?" ClientDescription="?"/>
  </soapenv:Body>
</soapenv:Envelope>

> {% client.global.set("auth_token", response.body.substr(response.body.indexOf("<AuthToken>") +11,  response.body.indexOf("</AuthToken>") -response.body.indexOf("<AuthToken>")-11  ) );
 client.log(response.body.substr(response.body.indexOf("<AuthToken>") +11,  response.body.indexOf("</AuthToken>") -response.body.indexOf("<AuthToken>")-11  ));
%}

###
POST https://e-invoicing.taxservice.am/api/services/services-by-id
accept: application/json
Content-Type: application/json
Cookie: jwt-auth-token={{auth_token}}

{
  "payload": {
    "id": "d8574468-5dee-4824-b755-be0b21844e91"
  }
}


###
POST https://e-invoicing.taxservice.am/api/services/services-create-draft
accept: application/json
Content-Type: application/json
Cookie: jwt-auth-token={{auth_token}}

{
  "payload": {
    "id": "00000000-0000-0000-0000-00000000013",
    "createdAt": "2022-12-16T09:54:18.476Z",
    "status": "DRAFT",
    "deliveredAt": "2022-12-16T00:00:00.000Z",
    "crmNo": "12345",
    "additionalInfo": "Lracucuch",
    "dealtAt": "2022-12-16T00:00:00.000Z",
    "dealNo": "hamar",
    "supplierTin": "00000019",
    "supplierVatTin": "00000019/1",
    "supplierName": " supplier Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ)",
    "supplierAddress": "ԱՐԱՐԱՏ ԱՐԱԼԵԶ ԱՐԱԼԵԶ ՎԱՐԴԱՆ ՄԱՄԻԿՈՆՅԱՆ Փ.1 9",
    "supplierBank": "Bank Name",
    "supplierAccNo": "Bank Account",
    "supplierAdditionalInfo": "Lracucich Tvyal",
    "buyerHasNoTin": false,
    "buyerIsNatural": false,
    "buyerTin": "00000019",
    "buyerVatTin": "00000019/1",
    "buyerName": "supplier Սահմանափակ պատասխանատվությամբ ընկերություն (ՍՊԸ)",
    "buyerAddress": "ԱՐԱՐԱՏ ԱՐԱԼԵԶ ԱՐԱԼԵԶ ՎԱՐԴԱՆ ՄԱՄԻԿՈՆՅԱՆ Փ.1 9",
    "items": [
      {
        "mode": "new",
        "invoiceId": "00000000-0000-0000-0000-00000000013",
        "id": "00000000-0000-0000-0000-00000000013",
        "seqNo": 1,
        "name": "name",
        "unit": "miavor",
        "quantity": 12,
        "unitPrice": 13,
        "discount": "",
        "totalValue": 156,
        "vatRate": "NONE",
        "vatAmount": 0,
        "total": 156
      }
    ],
    "totalValue": 156,
    "totalVatAmount": 0,
    "total": 156,
    "behalfOf": "SUPPLIER"
  }
}

###
POST https://e-invoicing.taxservice.am/api/invoice/invoice-list
accept: application/json
Content-Type: application/json
Cookie: jwt-auth-token={{auth_token}}

{"payload":{"condition":"((((#supplierTin = '00000019') or (#beneficiaryTin = '00000019')) and ((#status = 'ISSUED') or (#status = 'APPROVED'))) and (#type in ['EXCISE', 'GOODS', 'LEASING', 'SERVICES', 'VAT_RETURN']))","status":"ISSUED","pageLimit":5,"pageOffset":1,"sortCol":"createdAt","sortAsc":false}}





